# Generated by Django 3.1.3 on 2021-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/avatars/defaul-img.jpg', upload_to='user/avatars', verbose_name='avatar'),
        ),
    ]
