# Generated by Django 3.1.3 on 2021-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='home/festival', verbose_name='Image')),
                ('priority', models.CharField(choices=[('festival', 'Festival'), ('high-adv', 'High Priority Advertisement'), ('foursome-adv', 'Foursom Advertisement'), ('twosome-adv', 'Twosome Advertisement')], max_length=50, verbose_name='Priority')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('url', models.URLField(default='https://google.com', verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='home/shops', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('image', models.ImageField(upload_to='home/shops', verbose_name='Image')),
                ('action_url', models.URLField(default='http://127.0.0.1:8000', verbose_name='Action Url')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
