# Generated by Django 3.1.3 on 2021-01-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='home/festival', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivals',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='home/shops', verbose_name='Image')),
                ('action_url', models.URLField(default='http://127.0.0.1:8000', verbose_name='Action Url')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
