# Generated by Django 3.1.3 on 2021-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='home/festival', verbose_name='Image')),
                ('priority', models.CharField(choices=[('festival', 'Festival'), ('high-adv', 'High Priority Advertisement'), ('foursome-adv', 'Foursom Advertisement'), ('twosome-adv', 'Twosome Advertisement')], max_length=50, verbose_name='Priority')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivals',
            },
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
    ]
