# Generated by Django 3.1.3 on 2021-01-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_view', '0002_auto_20210108_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
    ]
