# Generated by Django 3.1.3 on 2021-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_view', '0005_auto_20210108_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='home/shops', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
