# Generated by Django 3.1.3 on 2021-01-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_view', '0006_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
