# Generated by Django 3.1.3 on 2021-01-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201231_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', related_query_name='shop_products', to='shop.shop', verbose_name='Shop'),
        ),
    ]
