# Generated by Django 3.1.3 on 2021-02-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210107_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'white'), ('pink', 'Pink'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], default='black', max_length=100, verbose_name='Color'),
        ),
    ]
