# Generated by Django 3.1.3 on 2021-02-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210107_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeta',
            name='label',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='value',
        ),
        migrations.AddField(
            model_name='productmeta',
            name='cach',
            field=models.CharField(default='0', max_length=50, verbose_name='Cach'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='cpu_manufacturer',
            field=models.CharField(default='None', max_length=50, verbose_name='CPU Manufacturer'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='cpu_model',
            field=models.CharField(default='None', max_length=50, verbose_name='CPU Model'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='cpu_series',
            field=models.CharField(default='None', max_length=50, verbose_name='CPU Series'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='cpu_speed',
            field=models.CharField(default='None', max_length=50, verbose_name='CPU Speed'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='gpu_manufacturer',
            field=models.CharField(default='None', max_length=50, verbose_name='GPU Manufacturer'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='gpu_model',
            field=models.CharField(default='None', max_length=50, verbose_name='GPU Model'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='gpu_ram',
            field=models.CharField(default='None', max_length=50, verbose_name='GPU RAM'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='ram_capacity',
            field=models.CharField(default='None', max_length=50, verbose_name='RAM Capacity'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='ram_type',
            field=models.CharField(default='None', max_length=50, verbose_name='RAM Type'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='size',
            field=models.CharField(default='None', max_length=50, verbose_name='Height Width Length'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='storage',
            field=models.CharField(default='None', max_length=50, verbose_name='Storage'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='storage_type',
            field=models.CharField(default='None', max_length=50, verbose_name='Storage Type'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='weight',
            field=models.CharField(default='None', max_length=50, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Foure'), (5, 'Five')], default=0, max_length=50, verbose_name='Rate'),
        ),
    ]
