# Generated by Django 3.1.3 on 2021-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210204_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(choices=[(0, 'صفر'), (1, 'یک'), (2, 'دو'), (3, 'سه'), (4, 'چهار'), (5, 'پنج')], default=0, verbose_name='Rate'),
        ),
    ]
