# Generated by Django 3.1.3 on 2021-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'white'), ('pink', 'Pink'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], default='black', max_length=100, verbose_name='Color'),
        ),
    ]
