# Generated by Django 3.1.3 on 2021-02-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210205_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeta',
            name='color',
        ),
    ]
