# Generated by Django 3.1.3 on 2021-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productmeta_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='display_accuracy',
            field=models.CharField(default='None', max_length=50, verbose_name='Display Accuracy'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='display_mate',
            field=models.BooleanField(default=False, verbose_name='Display Mate'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='display_size',
            field=models.CharField(default='None', max_length=50, verbose_name='Display Size'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='display_type',
            field=models.CharField(default='None', max_length=50, verbose_name='Display Type'),
        ),
    ]
