# Generated by Django 3.1.3 on 2021-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210209_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='display_touchable',
            field=models.BooleanField(default=False, verbose_name='Display Touchable'),
        ),
    ]
