# Generated by Django 3.1.3 on 2021-02-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmeta_display_touchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Product Type'),
        ),
    ]
