# Generated by Django 3.1.3 on 2021-02-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_brand_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Product Type'),
        ),
    ]
