# Generated by Django 3.1.3 on 2021-02-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210209_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product_type',
        ),
    ]
