# Generated by Django 3.1.3 on 2021-02-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_brand_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('sim_card_desc', models.CharField(max_length=50, verbose_name='Sim Card Descrioption')),
                ('weight', models.CharField(max_length=50, verbose_name='Weight')),
                ('body_structure', models.CharField(max_length=50, verbose_name='Body Structur')),
                ('special_properties', models.CharField(max_length=50, verbose_name='Special Properties')),
                ('num_sim_cards', models.CharField(max_length=50, verbose_name='Num of Sim Cards')),
                ('intro_date', models.DateTimeField(verbose_name='Introduction Date')),
                ('slot_for_sim', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='Slot For Sim')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('cpu_chipset', models.CharField(max_length=250, verbose_name='CPU Chipset')),
                ('cpu', models.CharField(max_length=250, verbose_name='CPU')),
                ('cpu_type', models.CharField(max_length=50, verbose_name='CPU Type')),
                ('cpu_freequency', models.CharField(max_length=50, verbose_name='CPU Frequency')),
                ('gpu', models.CharField(max_length=50, verbose_name='GPU')),
                ('ram', models.CharField(max_length=50, verbose_name='RAM')),
                ('ram_capacity', models.CharField(max_length=50, verbose_name='RAM Capacity')),
                ('side_storage', models.CharField(max_length=50, verbose_name='Side Storage')),
                ('side_storage_standard', models.CharField(max_length=50, verbose_name='Side Storage Standard')),
                ('colorful_display', models.CharField(choices=[('بلی', 'بلی'), ('خیر', 'خیر')], max_length=50, verbose_name='Colorful Storage')),
                ('touchable_display', models.CharField(choices=[('بلی', 'بلی'), ('خیر', 'خیر')], max_length=50, verbose_name='Touchable Display')),
                ('display_techno', models.CharField(max_length=50, verbose_name='Display Techni')),
                ('display_size_range', models.CharField(max_length=50, verbose_name='Display Size Range')),
                ('display_size', models.CharField(max_length=50, verbose_name='Display Size')),
                ('resolution', models.CharField(max_length=50, verbose_name='Resolution')),
                ('pixel_density', models.CharField(max_length=50, verbose_name='Pixel Density')),
                ('display_to_body', models.CharField(max_length=50, verbose_name='Display to Body')),
                ('display_ratio', models.CharField(max_length=50, verbose_name='Display Ratio')),
                ('networks', models.CharField(max_length=50, verbose_name='Networks')),
                ('network_2g', models.CharField(max_length=250, verbose_name='2G Network')),
                ('network_3g', models.CharField(max_length=250, verbose_name='3G Network')),
                ('network_4g', models.CharField(max_length=250, verbose_name='4G Network')),
                ('connection_technology', models.CharField(max_length=250, verbose_name='Connection Technology')),
                ('wifi', models.CharField(max_length=250, verbose_name='Wi-Fi')),
                ('bluetooth', models.CharField(max_length=250, verbose_name='Bluetooth')),
                ('location_techno', models.CharField(max_length=250, verbose_name='Location Technology')),
                ('port', models.CharField(max_length=250, verbose_name='Port')),
                ('back_camera_modules', models.CharField(max_length=50, verbose_name='Back Camera Modules')),
                ('image_resolution', models.CharField(max_length=50, verbose_name='Image Resolution')),
                ('flash', models.CharField(max_length=50, verbose_name='Flash')),
                ('camera_capabalities', models.TextField(verbose_name='Camera Capabalities')),
                ('filming', models.CharField(max_length=250, verbose_name='Filming')),
                ('selfie_camera', models.CharField(max_length=1024, verbose_name='Selfie Camera')),
                ('speaker', models.CharField(choices=[('بلی', 'بلی'), ('خیر', 'خیر')], max_length=50, verbose_name='Speaker')),
                ('voice_output', models.CharField(max_length=50, verbose_name='Voice Output')),
                ('os', models.CharField(max_length=50, verbose_name='OS')),
                ('os_release', models.CharField(max_length=50, verbose_name='OS Realease')),
                ('software_capabalities', models.TextField(verbose_name='Software Capabalities')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_meta', related_query_name='mobile_meta', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'MobileMeta',
                'verbose_name_plural': 'MobileMetas',
            },
        ),
    ]
